### ISSUE TITLE
cmd+I should open in the code editor instead of on top

### ISSUE THREAD

**Issue by nang-dev** [trypear/pearai-app#141] opened 2024-06-23 20:47 UTC
## Context

cmd+I opens on top:

<img width="901" alt="Screenshot 2024-06-23 at 4 44 02 PM" src="https://github.com/trypear/pearai-app/assets/5115108/da6bf272-8d0f-41c6-ad62-dac138a0ffa1">

but it should be like this: 

<img width="624" alt="Screenshot 2024-06-23 at 4 46 56 PM" src="https://github.com/trypear/pearai-app/assets/5115108/1db1a58a-b02a-4bc1-9cd5-178f9328a163">

**Comment by Mex777** [comment] 2024-06-29 14:43
This is a duplicate of https://github.com/trypear/pearai-app/issues/36

**Closed** 2024-07-12 04:31 UTC
Labels: UI/UX
